spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      # 클러스터 무력화
      cluster:
        nodes: ""
        max-redirects: 0

      # 단일 노드 가성비 레디스 주소로 덮어쓰기
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

      # TLS 암호화 활성화
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:true}

      # 클러스터 전용 기능 끄기
      lettuce:
        cluster:
          refresh:
            adaptive: false
            dynamic-refresh-sources: false
